<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <LangVersion>10.0</LangVersion>
    <RootNamespace>LianDian.Comm</RootNamespace>
    <AssemblyName>LianDian.Comm</AssemblyName>
    <Nullable>disable</Nullable>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="NModbus" Version="3.0.83" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\LianDian.Core\LianDian.Core.csproj" />
  </ItemGroup>
</Project>
