<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <LangVersion>10.0</LangVersion>
    <RootNamespace>LianDian.Core</RootNamespace>
    <AssemblyName>LianDian.Core</AssemblyName>
    <Nullable>disable</Nullable>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="log4net" Version="3.3.2" />
  </ItemGroup>
</Project>
